#!/bin/bash

# Use the 'pwd' command to get the current working directory
current_directory=$(pwd)

# Print the absolute path name of the current directory
echo "Current working directory: $current_directory"